spring.application.name=demo
spring.datasource.url=jdbc:postgresql://localhost:5432/biblioteca_db
spring.datasource.username=pan_con_manteca1122334455
spring.datasource.password=r4fmx4gjd0
spring.jpa.hibernate.ddl-auto=update
server.port=8081
